//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinfinityTools.Thinfinity.WebApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Thinfinity.WebApi.IWSThinRDP")]
    public interface IWSThinRDP {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message GetAllProfilesRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#GetAllProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.GetAllProfilesResponse GetAllProfiles(ThinfinityTools.Thinfinity.WebApi.GetAllProfilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#GetAllProfiles", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.GetAllProfilesResponse> GetAllProfilesAsync(ThinfinityTools.Thinfinity.WebApi.GetAllProfilesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message GetProfileCountRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#GetProfileCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.GetProfileCountResponse GetProfileCount(ThinfinityTools.Thinfinity.WebApi.GetProfileCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#GetProfileCount", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.GetProfileCountResponse> GetProfileCountAsync(ThinfinityTools.Thinfinity.WebApi.GetProfileCountRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message GetProfileRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#GetProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.GetProfileResponse GetProfile(ThinfinityTools.Thinfinity.WebApi.GetProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#GetProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.GetProfileResponse> GetProfileAsync(ThinfinityTools.Thinfinity.WebApi.GetProfileRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message FindByIDRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#FindByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.FindByIDResponse FindByID(ThinfinityTools.Thinfinity.WebApi.FindByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#FindByID", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.FindByIDResponse> FindByIDAsync(ThinfinityTools.Thinfinity.WebApi.FindByIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message FindByComputerRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#FindByComputer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.FindByComputerResponse FindByComputer(ThinfinityTools.Thinfinity.WebApi.FindByComputerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#FindByComputer", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.FindByComputerResponse> FindByComputerAsync(ThinfinityTools.Thinfinity.WebApi.FindByComputerRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message FindByUserNameRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#FindByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.FindByUserNameResponse FindByUserName(ThinfinityTools.Thinfinity.WebApi.FindByUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#FindByUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.FindByUserNameResponse> FindByUserNameAsync(ThinfinityTools.Thinfinity.WebApi.FindByUserNameRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message CreateProfileRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#CreateProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.CreateProfileResponse CreateProfile(ThinfinityTools.Thinfinity.WebApi.CreateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#CreateProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.CreateProfileResponse> CreateProfileAsync(ThinfinityTools.Thinfinity.WebApi.CreateProfileRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message DeleteProfileRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#DeleteProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.DeleteProfileResponse DeleteProfile(ThinfinityTools.Thinfinity.WebApi.DeleteProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#DeleteProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.DeleteProfileResponse> DeleteProfileAsync(ThinfinityTools.Thinfinity.WebApi.DeleteProfileRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message UpdateProfileRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#UpdateProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.UpdateProfileResponse UpdateProfile(ThinfinityTools.Thinfinity.WebApi.UpdateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#UpdateProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.UpdateProfileResponse> UpdateProfileAsync(ThinfinityTools.Thinfinity.WebApi.UpdateProfileRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message NewPublicKeyRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#NewPublicKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.NewPublicKeyResponse NewPublicKey(ThinfinityTools.Thinfinity.WebApi.NewPublicKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#NewPublicKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.NewPublicKeyResponse> NewPublicKeyAsync(ThinfinityTools.Thinfinity.WebApi.NewPublicKeyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message CommitRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#Commit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.CommitResponse Commit(ThinfinityTools.Thinfinity.WebApi.CommitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#Commit", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.CommitResponse> CommitAsync(ThinfinityTools.Thinfinity.WebApi.CommitRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ThinRDPWS.Admin.Intf-IWSThinRDP) of message RollbackRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#Rollback", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ThinfinityTools.Thinfinity.WebApi.RollbackResponse Rollback(ThinfinityTools.Thinfinity.WebApi.RollbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ThinRDPWS.Admin.Intf-IWSThinRDP#Rollback", ReplyAction="*")]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.RollbackResponse> RollbackAsync(ThinfinityTools.Thinfinity.WebApi.RollbackRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ThinRDPWS.Admin.Intf")]
    public partial class WSProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private bool enabledField;
        
        private bool unrestrictedField;
        
        private bool guestAllowedField;
        
        private bool isBuiltInField;
        
        private string publicKeyField;
        
        private string iconDataField;
        
        private string virtualPathField;
        
        private TProfileKind kindField;
        
        private string webLinkField;
        
        private string rdWebUrlField;
        
        private string computerField;
        
        private TRdpCredentials credentialsField;
        
        private string logonUserNameField;
        
        private string logonPasswordField;
        
        private TRdpScreenResolution screenResolutionField;
        
        private int screenWidthField;
        
        private int screenHeightField;
        
        private TRdpScreenBPP bPPField;
        
        private TRdpImageQuality imageQualityField;
        
        private bool unicodeKbdField;
        
        private bool consoleSessionField;
        
        private bool websocketCompressionField;
        
        private bool relativeMouseTouchField;
        
        private int keyboardLayoutField;
        
        private bool disableNLAField;
        
        private int dragDistanceField;
        
        private bool showOnStartField;
        
        private bool persistentCacheField;
        
        private bool enableRemoteFxField;
        
        private bool enableTouchRedirectionField;
        
        private int touchDragDelayField;
        
        private bool saveRDSessionsField;
        
        private bool smartSizingField;
        
        private TRdpAppMode appModeField;
        
        private string appCmdLineField;
        
        private string appCmdArgsField;
        
        private string appWorkDirField;
        
        private bool desktopBackgroundField;
        
        private bool visualStylesField;
        
        private bool menuAnimationField;
        
        private bool fontSmoothingField;
        
        private bool showWindowOnDragField;
        
        private bool desktopCompositionField;
        
        private string virtualMachineIDField;
        
        private string rDSCollectionURLField;
        
        private bool clipboardField;
        
        private bool printerEnabledField;
        
        private bool printerSetAsDefaultField;
        
        private string printerNameField;
        
        private string printerDriverField;
        
        private bool diskEnabledField;
        
        private string diskNameField;
        
        private bool diskAutoDownloadField;
        
        private bool soundEnabledField;
        
        private TRdpSoundQuality soundQualityField;
        
        private string usersField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        public bool Unrestricted {
            get {
                return this.unrestrictedField;
            }
            set {
                this.unrestrictedField = value;
                this.RaisePropertyChanged("Unrestricted");
            }
        }
        
        /// <remarks/>
        public bool GuestAllowed {
            get {
                return this.guestAllowedField;
            }
            set {
                this.guestAllowedField = value;
                this.RaisePropertyChanged("GuestAllowed");
            }
        }
        
        /// <remarks/>
        public bool IsBuiltIn {
            get {
                return this.isBuiltInField;
            }
            set {
                this.isBuiltInField = value;
                this.RaisePropertyChanged("IsBuiltIn");
            }
        }
        
        /// <remarks/>
        public string PublicKey {
            get {
                return this.publicKeyField;
            }
            set {
                this.publicKeyField = value;
                this.RaisePropertyChanged("PublicKey");
            }
        }
        
        /// <remarks/>
        public string IconData {
            get {
                return this.iconDataField;
            }
            set {
                this.iconDataField = value;
                this.RaisePropertyChanged("IconData");
            }
        }
        
        /// <remarks/>
        public string VirtualPath {
            get {
                return this.virtualPathField;
            }
            set {
                this.virtualPathField = value;
                this.RaisePropertyChanged("VirtualPath");
            }
        }
        
        /// <remarks/>
        public TProfileKind Kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
                this.RaisePropertyChanged("Kind");
            }
        }
        
        /// <remarks/>
        public string WebLink {
            get {
                return this.webLinkField;
            }
            set {
                this.webLinkField = value;
                this.RaisePropertyChanged("WebLink");
            }
        }
        
        /// <remarks/>
        public string RdWebUrl {
            get {
                return this.rdWebUrlField;
            }
            set {
                this.rdWebUrlField = value;
                this.RaisePropertyChanged("RdWebUrl");
            }
        }
        
        /// <remarks/>
        public string Computer {
            get {
                return this.computerField;
            }
            set {
                this.computerField = value;
                this.RaisePropertyChanged("Computer");
            }
        }
        
        /// <remarks/>
        public TRdpCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
                this.RaisePropertyChanged("Credentials");
            }
        }
        
        /// <remarks/>
        public string LogonUserName {
            get {
                return this.logonUserNameField;
            }
            set {
                this.logonUserNameField = value;
                this.RaisePropertyChanged("LogonUserName");
            }
        }
        
        /// <remarks/>
        public string LogonPassword {
            get {
                return this.logonPasswordField;
            }
            set {
                this.logonPasswordField = value;
                this.RaisePropertyChanged("LogonPassword");
            }
        }
        
        /// <remarks/>
        public TRdpScreenResolution ScreenResolution {
            get {
                return this.screenResolutionField;
            }
            set {
                this.screenResolutionField = value;
                this.RaisePropertyChanged("ScreenResolution");
            }
        }
        
        /// <remarks/>
        public int ScreenWidth {
            get {
                return this.screenWidthField;
            }
            set {
                this.screenWidthField = value;
                this.RaisePropertyChanged("ScreenWidth");
            }
        }
        
        /// <remarks/>
        public int ScreenHeight {
            get {
                return this.screenHeightField;
            }
            set {
                this.screenHeightField = value;
                this.RaisePropertyChanged("ScreenHeight");
            }
        }
        
        /// <remarks/>
        public TRdpScreenBPP BPP {
            get {
                return this.bPPField;
            }
            set {
                this.bPPField = value;
                this.RaisePropertyChanged("BPP");
            }
        }
        
        /// <remarks/>
        public TRdpImageQuality ImageQuality {
            get {
                return this.imageQualityField;
            }
            set {
                this.imageQualityField = value;
                this.RaisePropertyChanged("ImageQuality");
            }
        }
        
        /// <remarks/>
        public bool UnicodeKbd {
            get {
                return this.unicodeKbdField;
            }
            set {
                this.unicodeKbdField = value;
                this.RaisePropertyChanged("UnicodeKbd");
            }
        }
        
        /// <remarks/>
        public bool ConsoleSession {
            get {
                return this.consoleSessionField;
            }
            set {
                this.consoleSessionField = value;
                this.RaisePropertyChanged("ConsoleSession");
            }
        }
        
        /// <remarks/>
        public bool WebsocketCompression {
            get {
                return this.websocketCompressionField;
            }
            set {
                this.websocketCompressionField = value;
                this.RaisePropertyChanged("WebsocketCompression");
            }
        }
        
        /// <remarks/>
        public bool RelativeMouseTouch {
            get {
                return this.relativeMouseTouchField;
            }
            set {
                this.relativeMouseTouchField = value;
                this.RaisePropertyChanged("RelativeMouseTouch");
            }
        }
        
        /// <remarks/>
        public int KeyboardLayout {
            get {
                return this.keyboardLayoutField;
            }
            set {
                this.keyboardLayoutField = value;
                this.RaisePropertyChanged("KeyboardLayout");
            }
        }
        
        /// <remarks/>
        public bool DisableNLA {
            get {
                return this.disableNLAField;
            }
            set {
                this.disableNLAField = value;
                this.RaisePropertyChanged("DisableNLA");
            }
        }
        
        /// <remarks/>
        public int DragDistance {
            get {
                return this.dragDistanceField;
            }
            set {
                this.dragDistanceField = value;
                this.RaisePropertyChanged("DragDistance");
            }
        }
        
        /// <remarks/>
        public bool ShowOnStart {
            get {
                return this.showOnStartField;
            }
            set {
                this.showOnStartField = value;
                this.RaisePropertyChanged("ShowOnStart");
            }
        }
        
        /// <remarks/>
        public bool PersistentCache {
            get {
                return this.persistentCacheField;
            }
            set {
                this.persistentCacheField = value;
                this.RaisePropertyChanged("PersistentCache");
            }
        }
        
        /// <remarks/>
        public bool EnableRemoteFx {
            get {
                return this.enableRemoteFxField;
            }
            set {
                this.enableRemoteFxField = value;
                this.RaisePropertyChanged("EnableRemoteFx");
            }
        }
        
        /// <remarks/>
        public bool EnableTouchRedirection {
            get {
                return this.enableTouchRedirectionField;
            }
            set {
                this.enableTouchRedirectionField = value;
                this.RaisePropertyChanged("EnableTouchRedirection");
            }
        }
        
        /// <remarks/>
        public int TouchDragDelay {
            get {
                return this.touchDragDelayField;
            }
            set {
                this.touchDragDelayField = value;
                this.RaisePropertyChanged("TouchDragDelay");
            }
        }
        
        /// <remarks/>
        public bool SaveRDSessions {
            get {
                return this.saveRDSessionsField;
            }
            set {
                this.saveRDSessionsField = value;
                this.RaisePropertyChanged("SaveRDSessions");
            }
        }
        
        /// <remarks/>
        public bool SmartSizing {
            get {
                return this.smartSizingField;
            }
            set {
                this.smartSizingField = value;
                this.RaisePropertyChanged("SmartSizing");
            }
        }
        
        /// <remarks/>
        public TRdpAppMode AppMode {
            get {
                return this.appModeField;
            }
            set {
                this.appModeField = value;
                this.RaisePropertyChanged("AppMode");
            }
        }
        
        /// <remarks/>
        public string AppCmdLine {
            get {
                return this.appCmdLineField;
            }
            set {
                this.appCmdLineField = value;
                this.RaisePropertyChanged("AppCmdLine");
            }
        }
        
        /// <remarks/>
        public string AppCmdArgs {
            get {
                return this.appCmdArgsField;
            }
            set {
                this.appCmdArgsField = value;
                this.RaisePropertyChanged("AppCmdArgs");
            }
        }
        
        /// <remarks/>
        public string AppWorkDir {
            get {
                return this.appWorkDirField;
            }
            set {
                this.appWorkDirField = value;
                this.RaisePropertyChanged("AppWorkDir");
            }
        }
        
        /// <remarks/>
        public bool DesktopBackground {
            get {
                return this.desktopBackgroundField;
            }
            set {
                this.desktopBackgroundField = value;
                this.RaisePropertyChanged("DesktopBackground");
            }
        }
        
        /// <remarks/>
        public bool VisualStyles {
            get {
                return this.visualStylesField;
            }
            set {
                this.visualStylesField = value;
                this.RaisePropertyChanged("VisualStyles");
            }
        }
        
        /// <remarks/>
        public bool MenuAnimation {
            get {
                return this.menuAnimationField;
            }
            set {
                this.menuAnimationField = value;
                this.RaisePropertyChanged("MenuAnimation");
            }
        }
        
        /// <remarks/>
        public bool FontSmoothing {
            get {
                return this.fontSmoothingField;
            }
            set {
                this.fontSmoothingField = value;
                this.RaisePropertyChanged("FontSmoothing");
            }
        }
        
        /// <remarks/>
        public bool ShowWindowOnDrag {
            get {
                return this.showWindowOnDragField;
            }
            set {
                this.showWindowOnDragField = value;
                this.RaisePropertyChanged("ShowWindowOnDrag");
            }
        }
        
        /// <remarks/>
        public bool DesktopComposition {
            get {
                return this.desktopCompositionField;
            }
            set {
                this.desktopCompositionField = value;
                this.RaisePropertyChanged("DesktopComposition");
            }
        }
        
        /// <remarks/>
        public string VirtualMachineID {
            get {
                return this.virtualMachineIDField;
            }
            set {
                this.virtualMachineIDField = value;
                this.RaisePropertyChanged("VirtualMachineID");
            }
        }
        
        /// <remarks/>
        public string RDSCollectionURL {
            get {
                return this.rDSCollectionURLField;
            }
            set {
                this.rDSCollectionURLField = value;
                this.RaisePropertyChanged("RDSCollectionURL");
            }
        }
        
        /// <remarks/>
        public bool Clipboard {
            get {
                return this.clipboardField;
            }
            set {
                this.clipboardField = value;
                this.RaisePropertyChanged("Clipboard");
            }
        }
        
        /// <remarks/>
        public bool PrinterEnabled {
            get {
                return this.printerEnabledField;
            }
            set {
                this.printerEnabledField = value;
                this.RaisePropertyChanged("PrinterEnabled");
            }
        }
        
        /// <remarks/>
        public bool PrinterSetAsDefault {
            get {
                return this.printerSetAsDefaultField;
            }
            set {
                this.printerSetAsDefaultField = value;
                this.RaisePropertyChanged("PrinterSetAsDefault");
            }
        }
        
        /// <remarks/>
        public string PrinterName {
            get {
                return this.printerNameField;
            }
            set {
                this.printerNameField = value;
                this.RaisePropertyChanged("PrinterName");
            }
        }
        
        /// <remarks/>
        public string PrinterDriver {
            get {
                return this.printerDriverField;
            }
            set {
                this.printerDriverField = value;
                this.RaisePropertyChanged("PrinterDriver");
            }
        }
        
        /// <remarks/>
        public bool DiskEnabled {
            get {
                return this.diskEnabledField;
            }
            set {
                this.diskEnabledField = value;
                this.RaisePropertyChanged("DiskEnabled");
            }
        }
        
        /// <remarks/>
        public string DiskName {
            get {
                return this.diskNameField;
            }
            set {
                this.diskNameField = value;
                this.RaisePropertyChanged("DiskName");
            }
        }
        
        /// <remarks/>
        public bool DiskAutoDownload {
            get {
                return this.diskAutoDownloadField;
            }
            set {
                this.diskAutoDownloadField = value;
                this.RaisePropertyChanged("DiskAutoDownload");
            }
        }
        
        /// <remarks/>
        public bool SoundEnabled {
            get {
                return this.soundEnabledField;
            }
            set {
                this.soundEnabledField = value;
                this.RaisePropertyChanged("SoundEnabled");
            }
        }
        
        /// <remarks/>
        public TRdpSoundQuality SoundQuality {
            get {
                return this.soundQualityField;
            }
            set {
                this.soundQualityField = value;
                this.RaisePropertyChanged("SoundQuality");
            }
        }
        
        /// <remarks/>
        public string Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
                this.RaisePropertyChanged("Users");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ThinRDP.Profiles")]
    public enum TProfileKind {
        
        /// <remarks/>
        pkRDPProfile,
        
        /// <remarks/>
        pkWebLink,
        
        /// <remarks/>
        pkRdWeb,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ThinRDP.Common")]
    public enum TRdpCredentials {
        
        /// <remarks/>
        crAuthenticated,
        
        /// <remarks/>
        crAsk,
        
        /// <remarks/>
        crSaved,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ThinRDP.Common")]
    public enum TRdpScreenResolution {
        
        /// <remarks/>
        srCustom,
        
        /// <remarks/>
        srFitToBrowser,
        
        /// <remarks/>
        srFitToScreen,
        
        /// <remarks/>
        sr640x480,
        
        /// <remarks/>
        sr800x600,
        
        /// <remarks/>
        sr1024x768,
        
        /// <remarks/>
        sr1280x720,
        
        /// <remarks/>
        sr1280x768,
        
        /// <remarks/>
        sr1280x1024,
        
        /// <remarks/>
        sr1440x900,
        
        /// <remarks/>
        sr1440x1050,
        
        /// <remarks/>
        sr1600x1200,
        
        /// <remarks/>
        sr1680x1050,
        
        /// <remarks/>
        sr1920x1080,
        
        /// <remarks/>
        sr1920x1200,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ThinRDP.Common")]
    public enum TRdpScreenBPP {
        
        /// <remarks/>
        bpp8,
        
        /// <remarks/>
        bpp15,
        
        /// <remarks/>
        bpp16,
        
        /// <remarks/>
        bpp24,
        
        /// <remarks/>
        bpp32,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ThinRDP.Common")]
    public enum TRdpImageQuality {
        
        /// <remarks/>
        iqHighest,
        
        /// <remarks/>
        iqOptimal,
        
        /// <remarks/>
        iqGood,
        
        /// <remarks/>
        iqFaster,
        
        /// <remarks/>
        iqNative,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ThinRDP.Common")]
    public enum TRdpAppMode {
        
        /// <remarks/>
        amNone,
        
        /// <remarks/>
        amStartApp,
        
        /// <remarks/>
        amRemoteApp,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ThinRDP.Common")]
    public enum TRdpSoundQuality {
        
        /// <remarks/>
        sqExcellent,
        
        /// <remarks/>
        sqOptimal,
        
        /// <remarks/>
        sqGood,
        
        /// <remarks/>
        sqPoor,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllProfiles", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class GetAllProfilesRequest {
        
        public GetAllProfilesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllProfilesResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class GetAllProfilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ThinfinityTools.Thinfinity.WebApi.WSProfile[] @return;
        
        public GetAllProfilesResponse() {
        }
        
        public GetAllProfilesResponse(ThinfinityTools.Thinfinity.WebApi.WSProfile[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProfileCount", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class GetProfileCountRequest {
        
        public GetProfileCountRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProfileCountResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class GetProfileCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public GetProfileCountResponse() {
        }
        
        public GetProfileCountResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProfile", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class GetProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Index;
        
        public GetProfileRequest() {
        }
        
        public GetProfileRequest(int Index) {
            this.Index = Index;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProfileResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class GetProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ThinfinityTools.Thinfinity.WebApi.WSProfile @return;
        
        public GetProfileResponse() {
        }
        
        public GetProfileResponse(ThinfinityTools.Thinfinity.WebApi.WSProfile @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByID", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class FindByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ID;
        
        public FindByIDRequest() {
        }
        
        public FindByIDRequest(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByIDResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class FindByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ThinfinityTools.Thinfinity.WebApi.WSProfile @return;
        
        public FindByIDResponse() {
        }
        
        public FindByIDResponse(ThinfinityTools.Thinfinity.WebApi.WSProfile @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByComputer", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class FindByComputerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Computer;
        
        public FindByComputerRequest() {
        }
        
        public FindByComputerRequest(string Computer) {
            this.Computer = Computer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByComputerResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class FindByComputerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ThinfinityTools.Thinfinity.WebApi.WSProfile[] @return;
        
        public FindByComputerResponse() {
        }
        
        public FindByComputerResponse(ThinfinityTools.Thinfinity.WebApi.WSProfile[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByUserName", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class FindByUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string UserName;
        
        public FindByUserNameRequest() {
        }
        
        public FindByUserNameRequest(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByUserNameResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class FindByUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ThinfinityTools.Thinfinity.WebApi.WSProfile[] @return;
        
        public FindByUserNameResponse() {
        }
        
        public FindByUserNameResponse(ThinfinityTools.Thinfinity.WebApi.WSProfile[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProfile", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class CreateProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ThinfinityTools.Thinfinity.WebApi.WSProfile Profile;
        
        public CreateProfileRequest() {
        }
        
        public CreateProfileRequest(ThinfinityTools.Thinfinity.WebApi.WSProfile Profile) {
            this.Profile = Profile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProfileResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class CreateProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ThinfinityTools.Thinfinity.WebApi.WSProfile @return;
        
        public CreateProfileResponse() {
        }
        
        public CreateProfileResponse(ThinfinityTools.Thinfinity.WebApi.WSProfile @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteProfile", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class DeleteProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ID;
        
        public DeleteProfileRequest() {
        }
        
        public DeleteProfileRequest(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteProfileResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class DeleteProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public DeleteProfileResponse() {
        }
        
        public DeleteProfileResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateProfile", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class UpdateProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ThinfinityTools.Thinfinity.WebApi.WSProfile Profile;
        
        public UpdateProfileRequest() {
        }
        
        public UpdateProfileRequest(ThinfinityTools.Thinfinity.WebApi.WSProfile Profile) {
            this.Profile = Profile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateProfileResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class UpdateProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public UpdateProfileResponse() {
        }
        
        public UpdateProfileResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewPublicKey", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class NewPublicKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ID;
        
        public NewPublicKeyRequest() {
        }
        
        public NewPublicKeyRequest(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewPublicKeyResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class NewPublicKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ThinfinityTools.Thinfinity.WebApi.WSProfile @return;
        
        public NewPublicKeyResponse() {
        }
        
        public NewPublicKeyResponse(ThinfinityTools.Thinfinity.WebApi.WSProfile @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Commit", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class CommitRequest {
        
        public CommitRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CommitResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class CommitResponse {
        
        public CommitResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Rollback", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class RollbackRequest {
        
        public RollbackRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RollbackResponse", WrapperNamespace="urn:ThinRDPWS.Admin.Intf-IWSThinRDP", IsWrapped=true)]
    public partial class RollbackResponse {
        
        public RollbackResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSThinRDPChannel : ThinfinityTools.Thinfinity.WebApi.IWSThinRDP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSThinRDPClient : System.ServiceModel.ClientBase<ThinfinityTools.Thinfinity.WebApi.IWSThinRDP>, ThinfinityTools.Thinfinity.WebApi.IWSThinRDP {
        
        public WSThinRDPClient() {
        }
        
        public WSThinRDPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSThinRDPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSThinRDPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSThinRDPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.GetAllProfilesResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.GetAllProfiles(ThinfinityTools.Thinfinity.WebApi.GetAllProfilesRequest request) {
            return base.Channel.GetAllProfiles(request);
        }
        
        public ThinfinityTools.Thinfinity.WebApi.WSProfile[] GetAllProfiles() {
            ThinfinityTools.Thinfinity.WebApi.GetAllProfilesRequest inValue = new ThinfinityTools.Thinfinity.WebApi.GetAllProfilesRequest();
            ThinfinityTools.Thinfinity.WebApi.GetAllProfilesResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).GetAllProfiles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.GetAllProfilesResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.GetAllProfilesAsync(ThinfinityTools.Thinfinity.WebApi.GetAllProfilesRequest request) {
            return base.Channel.GetAllProfilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.GetAllProfilesResponse> GetAllProfilesAsync() {
            ThinfinityTools.Thinfinity.WebApi.GetAllProfilesRequest inValue = new ThinfinityTools.Thinfinity.WebApi.GetAllProfilesRequest();
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).GetAllProfilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.GetProfileCountResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.GetProfileCount(ThinfinityTools.Thinfinity.WebApi.GetProfileCountRequest request) {
            return base.Channel.GetProfileCount(request);
        }
        
        public int GetProfileCount() {
            ThinfinityTools.Thinfinity.WebApi.GetProfileCountRequest inValue = new ThinfinityTools.Thinfinity.WebApi.GetProfileCountRequest();
            ThinfinityTools.Thinfinity.WebApi.GetProfileCountResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).GetProfileCount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.GetProfileCountResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.GetProfileCountAsync(ThinfinityTools.Thinfinity.WebApi.GetProfileCountRequest request) {
            return base.Channel.GetProfileCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.GetProfileCountResponse> GetProfileCountAsync() {
            ThinfinityTools.Thinfinity.WebApi.GetProfileCountRequest inValue = new ThinfinityTools.Thinfinity.WebApi.GetProfileCountRequest();
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).GetProfileCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.GetProfileResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.GetProfile(ThinfinityTools.Thinfinity.WebApi.GetProfileRequest request) {
            return base.Channel.GetProfile(request);
        }
        
        public ThinfinityTools.Thinfinity.WebApi.WSProfile GetProfile(int Index) {
            ThinfinityTools.Thinfinity.WebApi.GetProfileRequest inValue = new ThinfinityTools.Thinfinity.WebApi.GetProfileRequest();
            inValue.Index = Index;
            ThinfinityTools.Thinfinity.WebApi.GetProfileResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).GetProfile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.GetProfileResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.GetProfileAsync(ThinfinityTools.Thinfinity.WebApi.GetProfileRequest request) {
            return base.Channel.GetProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.GetProfileResponse> GetProfileAsync(int Index) {
            ThinfinityTools.Thinfinity.WebApi.GetProfileRequest inValue = new ThinfinityTools.Thinfinity.WebApi.GetProfileRequest();
            inValue.Index = Index;
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).GetProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.FindByIDResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.FindByID(ThinfinityTools.Thinfinity.WebApi.FindByIDRequest request) {
            return base.Channel.FindByID(request);
        }
        
        public ThinfinityTools.Thinfinity.WebApi.WSProfile FindByID(string ID) {
            ThinfinityTools.Thinfinity.WebApi.FindByIDRequest inValue = new ThinfinityTools.Thinfinity.WebApi.FindByIDRequest();
            inValue.ID = ID;
            ThinfinityTools.Thinfinity.WebApi.FindByIDResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).FindByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.FindByIDResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.FindByIDAsync(ThinfinityTools.Thinfinity.WebApi.FindByIDRequest request) {
            return base.Channel.FindByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.FindByIDResponse> FindByIDAsync(string ID) {
            ThinfinityTools.Thinfinity.WebApi.FindByIDRequest inValue = new ThinfinityTools.Thinfinity.WebApi.FindByIDRequest();
            inValue.ID = ID;
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).FindByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.FindByComputerResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.FindByComputer(ThinfinityTools.Thinfinity.WebApi.FindByComputerRequest request) {
            return base.Channel.FindByComputer(request);
        }
        
        public ThinfinityTools.Thinfinity.WebApi.WSProfile[] FindByComputer(string Computer) {
            ThinfinityTools.Thinfinity.WebApi.FindByComputerRequest inValue = new ThinfinityTools.Thinfinity.WebApi.FindByComputerRequest();
            inValue.Computer = Computer;
            ThinfinityTools.Thinfinity.WebApi.FindByComputerResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).FindByComputer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.FindByComputerResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.FindByComputerAsync(ThinfinityTools.Thinfinity.WebApi.FindByComputerRequest request) {
            return base.Channel.FindByComputerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.FindByComputerResponse> FindByComputerAsync(string Computer) {
            ThinfinityTools.Thinfinity.WebApi.FindByComputerRequest inValue = new ThinfinityTools.Thinfinity.WebApi.FindByComputerRequest();
            inValue.Computer = Computer;
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).FindByComputerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.FindByUserNameResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.FindByUserName(ThinfinityTools.Thinfinity.WebApi.FindByUserNameRequest request) {
            return base.Channel.FindByUserName(request);
        }
        
        public ThinfinityTools.Thinfinity.WebApi.WSProfile[] FindByUserName(string UserName) {
            ThinfinityTools.Thinfinity.WebApi.FindByUserNameRequest inValue = new ThinfinityTools.Thinfinity.WebApi.FindByUserNameRequest();
            inValue.UserName = UserName;
            ThinfinityTools.Thinfinity.WebApi.FindByUserNameResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).FindByUserName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.FindByUserNameResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.FindByUserNameAsync(ThinfinityTools.Thinfinity.WebApi.FindByUserNameRequest request) {
            return base.Channel.FindByUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.FindByUserNameResponse> FindByUserNameAsync(string UserName) {
            ThinfinityTools.Thinfinity.WebApi.FindByUserNameRequest inValue = new ThinfinityTools.Thinfinity.WebApi.FindByUserNameRequest();
            inValue.UserName = UserName;
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).FindByUserNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.CreateProfileResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.CreateProfile(ThinfinityTools.Thinfinity.WebApi.CreateProfileRequest request) {
            return base.Channel.CreateProfile(request);
        }
        
        public ThinfinityTools.Thinfinity.WebApi.WSProfile CreateProfile(ThinfinityTools.Thinfinity.WebApi.WSProfile Profile) {
            ThinfinityTools.Thinfinity.WebApi.CreateProfileRequest inValue = new ThinfinityTools.Thinfinity.WebApi.CreateProfileRequest();
            inValue.Profile = Profile;
            ThinfinityTools.Thinfinity.WebApi.CreateProfileResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).CreateProfile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.CreateProfileResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.CreateProfileAsync(ThinfinityTools.Thinfinity.WebApi.CreateProfileRequest request) {
            return base.Channel.CreateProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.CreateProfileResponse> CreateProfileAsync(ThinfinityTools.Thinfinity.WebApi.WSProfile Profile) {
            ThinfinityTools.Thinfinity.WebApi.CreateProfileRequest inValue = new ThinfinityTools.Thinfinity.WebApi.CreateProfileRequest();
            inValue.Profile = Profile;
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).CreateProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.DeleteProfileResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.DeleteProfile(ThinfinityTools.Thinfinity.WebApi.DeleteProfileRequest request) {
            return base.Channel.DeleteProfile(request);
        }
        
        public bool DeleteProfile(string ID) {
            ThinfinityTools.Thinfinity.WebApi.DeleteProfileRequest inValue = new ThinfinityTools.Thinfinity.WebApi.DeleteProfileRequest();
            inValue.ID = ID;
            ThinfinityTools.Thinfinity.WebApi.DeleteProfileResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).DeleteProfile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.DeleteProfileResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.DeleteProfileAsync(ThinfinityTools.Thinfinity.WebApi.DeleteProfileRequest request) {
            return base.Channel.DeleteProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.DeleteProfileResponse> DeleteProfileAsync(string ID) {
            ThinfinityTools.Thinfinity.WebApi.DeleteProfileRequest inValue = new ThinfinityTools.Thinfinity.WebApi.DeleteProfileRequest();
            inValue.ID = ID;
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).DeleteProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.UpdateProfileResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.UpdateProfile(ThinfinityTools.Thinfinity.WebApi.UpdateProfileRequest request) {
            return base.Channel.UpdateProfile(request);
        }
        
        public int UpdateProfile(ThinfinityTools.Thinfinity.WebApi.WSProfile Profile) {
            ThinfinityTools.Thinfinity.WebApi.UpdateProfileRequest inValue = new ThinfinityTools.Thinfinity.WebApi.UpdateProfileRequest();
            inValue.Profile = Profile;
            ThinfinityTools.Thinfinity.WebApi.UpdateProfileResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).UpdateProfile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.UpdateProfileResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.UpdateProfileAsync(ThinfinityTools.Thinfinity.WebApi.UpdateProfileRequest request) {
            return base.Channel.UpdateProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.UpdateProfileResponse> UpdateProfileAsync(ThinfinityTools.Thinfinity.WebApi.WSProfile Profile) {
            ThinfinityTools.Thinfinity.WebApi.UpdateProfileRequest inValue = new ThinfinityTools.Thinfinity.WebApi.UpdateProfileRequest();
            inValue.Profile = Profile;
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).UpdateProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.NewPublicKeyResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.NewPublicKey(ThinfinityTools.Thinfinity.WebApi.NewPublicKeyRequest request) {
            return base.Channel.NewPublicKey(request);
        }
        
        public ThinfinityTools.Thinfinity.WebApi.WSProfile NewPublicKey(string ID) {
            ThinfinityTools.Thinfinity.WebApi.NewPublicKeyRequest inValue = new ThinfinityTools.Thinfinity.WebApi.NewPublicKeyRequest();
            inValue.ID = ID;
            ThinfinityTools.Thinfinity.WebApi.NewPublicKeyResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).NewPublicKey(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.NewPublicKeyResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.NewPublicKeyAsync(ThinfinityTools.Thinfinity.WebApi.NewPublicKeyRequest request) {
            return base.Channel.NewPublicKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.NewPublicKeyResponse> NewPublicKeyAsync(string ID) {
            ThinfinityTools.Thinfinity.WebApi.NewPublicKeyRequest inValue = new ThinfinityTools.Thinfinity.WebApi.NewPublicKeyRequest();
            inValue.ID = ID;
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).NewPublicKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.CommitResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.Commit(ThinfinityTools.Thinfinity.WebApi.CommitRequest request) {
            return base.Channel.Commit(request);
        }
        
        public void Commit() {
            ThinfinityTools.Thinfinity.WebApi.CommitRequest inValue = new ThinfinityTools.Thinfinity.WebApi.CommitRequest();
            ThinfinityTools.Thinfinity.WebApi.CommitResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).Commit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.CommitResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.CommitAsync(ThinfinityTools.Thinfinity.WebApi.CommitRequest request) {
            return base.Channel.CommitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.CommitResponse> CommitAsync() {
            ThinfinityTools.Thinfinity.WebApi.CommitRequest inValue = new ThinfinityTools.Thinfinity.WebApi.CommitRequest();
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).CommitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThinfinityTools.Thinfinity.WebApi.RollbackResponse ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.Rollback(ThinfinityTools.Thinfinity.WebApi.RollbackRequest request) {
            return base.Channel.Rollback(request);
        }
        
        public void Rollback() {
            ThinfinityTools.Thinfinity.WebApi.RollbackRequest inValue = new ThinfinityTools.Thinfinity.WebApi.RollbackRequest();
            ThinfinityTools.Thinfinity.WebApi.RollbackResponse retVal = ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).Rollback(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.RollbackResponse> ThinfinityTools.Thinfinity.WebApi.IWSThinRDP.RollbackAsync(ThinfinityTools.Thinfinity.WebApi.RollbackRequest request) {
            return base.Channel.RollbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThinfinityTools.Thinfinity.WebApi.RollbackResponse> RollbackAsync() {
            ThinfinityTools.Thinfinity.WebApi.RollbackRequest inValue = new ThinfinityTools.Thinfinity.WebApi.RollbackRequest();
            return ((ThinfinityTools.Thinfinity.WebApi.IWSThinRDP)(this)).RollbackAsync(inValue);
        }
    }
}
